// <auto-generated />
using System;
using Immigratiom.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Immigratiom.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230710062028_creatingallmodelrequired")]
    partial class creatingallmodelrequired
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Immigratiom.DAL.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApplicantsID")
                        .HasColumnType("int");

                    b.Property<int>("OfficerID")
                        .HasColumnType("int");

                    b.Property<int>("ResponseID")
                        .HasColumnType("int");

                    b.HasKey("AdminID");

                    b.HasIndex("ApplicantsID");

                    b.HasIndex("OfficerID");

                    b.HasIndex("ResponseID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Immigratiom.DAL.Models.Applicants", b =>
                {
                    b.Property<int>("ApplicantsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("FIRNumber")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasCriminalRecord")
                        .HasColumnType("bit");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PassportExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurposeID")
                        .HasColumnType("int");

                    b.Property<string>("PurposeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitingCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicantsID");

                    b.HasIndex("PurposeID");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("Immigratiom.DAL.Models.Officers", b =>
                {
                    b.Property<int>("OfficerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ApplicantsID")
                        .HasColumnType("int");

                    b.Property<string>("OfficerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponseID")
                        .HasColumnType("int");

                    b.HasKey("OfficerID");

                    b.HasIndex("ApplicantsID");

                    b.HasIndex("ResponseID");

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("Immigratiom.DAL.Models.Purpose", b =>
                {
                    b.Property<int>("PurposeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VisaCharges")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurposeID");

                    b.ToTable("Purpose");
                });

            modelBuilder.Entity("Immigratiom.DAL.Models.Response", b =>
                {
                    b.Property<int>("ResponseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResponseID");

                    b.ToTable("Response");
                });

            modelBuilder.Entity("Immigratiom.DAL.Models.Admin", b =>
                {
                    b.HasOne("Immigratiom.DAL.Models.Applicants", "applicants")
                        .WithMany()
                        .HasForeignKey("ApplicantsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Immigratiom.DAL.Models.Officers", "officers")
                        .WithMany()
                        .HasForeignKey("OfficerID")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("Immigratiom.DAL.Models.Response", "response")
                        .WithMany()
                        .HasForeignKey("ResponseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("applicants");

                    b.Navigation("officers");

                    b.Navigation("response");
                });

            modelBuilder.Entity("Immigratiom.DAL.Models.Applicants", b =>
                {
                    b.HasOne("Immigratiom.DAL.Models.Purpose", "purpose")
                        .WithMany()
                        .HasForeignKey("PurposeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("purpose");
                });

            modelBuilder.Entity("Immigratiom.DAL.Models.Officers", b =>
                {
                    b.HasOne("Immigratiom.DAL.Models.Applicants", "applicants")
                        .WithMany()
                        .HasForeignKey("ApplicantsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Immigratiom.DAL.Models.Response", "response")
                        .WithMany()
                        .HasForeignKey("ResponseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("applicants");

                    b.Navigation("response");
                });
#pragma warning restore 612, 618
        }
    }
}
